name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Flake8
      uses: tayfun/flake8-your-pr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: actions/docker/cli@master
      with:
        args: build .
